language: node_js
node_js:
- '0.10'
script:
  - jshint *.js
  - npm test
notifications:
  email: false
  irc:
    channels:
      - "irc.mozilla.org#standup"
    on_success: change
    on_failure: always
