services: docker
env:
  global:
    - DOCKER_REGISTRY=registry.heroku.com
    - HEROKU_PROD_APP=standups-irc
    - HEROKU_STAGE_APP=standupstage-irc
    - HEROKU_PROC_TYPE=worker
    - DOCKER_CACHE_FILE=/home/travis/docker/cache.tar.gz
cache:
  directories:
    - /home/travis/docker/
before_install:
  - docker -v
  - docker-compose -v
  - echo "ENV GIT_SHA ${TRAVIS_COMMIT}" >> Dockerfile
  - bin/travis-docker-cache.sh load
install: make build
script:
  - make lint-image
  - make test-image
  - bin/travis-docker-cache.sh save
notifications:
  email: false
  irc:
    channels:
      - "irc.mozilla.org#standup"
    on_success: change
    on_failure: always
